const api = window.CollegeBuddyAPI;
const state = { user: null, resources: [], events: [], reports: [], courses: [], resourceType: '' };
const titles = { home:['Campus overview','Home'], courses:['Academic catalog','Courses'], resources:['Knowledge library','Resources'], events:['Campus pulse','Events'], 'lost-found':['Community board','Lost & Found'], profile:['Your account','Profile'], settings:['Local preferences','Settings'], admin:['Restricted workspace','Admin center'] };

const text = (value, fallback = '—') => value === undefined || value === null || value === '' ? fallback : String(value);
const formatDate = (value) => value ? new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}) : 'Date TBA';
const initials = (name) => text(name,'Student').split(/\s+/).slice(0,2).map((part)=>part[0]).join('').toUpperCase();
function clear(element){ while(element.firstChild) element.removeChild(element.firstChild); }
function el(tag,className,content){ const node=document.createElement(tag); if(className) node.className=className; if(content!==undefined) node.textContent=text(content); return node; }
function empty(container,title,detail){ clear(container); const node=el('div','empty-state'); node.append(el('strong','',title),document.createTextNode(detail)); container.append(node); }
function notice(message){ const node=document.getElementById('globalNotice'); node.textContent=message; node.classList.toggle('hidden',!message); }

function listItem(icon,title,meta,date){ const row=el('article','list-item'); row.append(el('span','item-icon',icon)); const copy=el('div','list-copy'); copy.append(el('strong','',title),el('small','',meta)); row.append(copy,el('time','',date)); return row; }
function renderHome(){
  const metrics=document.getElementById('metrics'); clear(metrics);
  [['Courses',state.courses.length],['Resources',state.resources.length],['Upcoming',state.events.length],['Open reports',state.reports.filter((item)=>item.status==='Open').length]].forEach(([label,value])=>{const card=el('div','metric');card.append(el('i'),el('span','',label),el('strong','',value));metrics.append(card)});
  const events=document.getElementById('homeEvents');clear(events);state.events.slice(0,4).forEach((item)=>events.append(listItem('◷',item.title,`${text(item.type,'event')} · ${text(item.location,'Campus')}`,formatDate(item.eventDate))));if(!state.events.length)empty(events,'No upcoming events','Campus events will appear here.');
  const resources=document.getElementById('homeResources');clear(resources);state.resources.slice(0,4).forEach((item)=>resources.append(listItem('◇',item.title,`${text(item.courseId)} · ${text(item.resourceType,'resource').replaceAll('_',' ')}`,item.status||'approved')));if(!state.resources.length)empty(resources,'No resources yet','Approved uploads and your submissions will appear here.');
  const reports=document.getElementById('homeLostFound');clear(reports);state.reports.slice(0,3).forEach((item)=>{const card=el('article','mini-card');card.append(el('span','',item.type),el('h3','',item.title),el('p','',`${text(item.location)} · ${text(item.status)}`));reports.append(card)});if(!state.reports.length)empty(reports,'The board is clear','New lost-and-found reports will appear here.');
}
function renderTiles(containerId,items,renderer,emptyTitle){const container=document.getElementById(containerId);clear(container);items.forEach((item)=>container.append(renderer(item)));if(!items.length)empty(container,emptyTitle,'Try adjusting the filters or check back later.');}
function baseTile(label,title,description){const card=el('article','tile');card.append(el('span','badge',label),el('h3','',title),el('p','',description));return card;}
function renderCourses(){renderTiles('coursesGrid',state.courses,(item)=>{const card=baseTile(item.code,item.name,`${item.department} · Semester ${item.semester}`);const foot=el('footer');foot.append(el('span','',`${text(item.credits,0)} credits`),el('span','',item.active===false?'Archived':'Active'));card.append(foot);return card},'No courses found');}
function renderResources(){renderTiles('resourcesGrid',state.resources,(item)=>{const card=baseTile(text(item.resourceType,'resource').replaceAll('_',' '),item.title,`${text(item.courseId)} · Semester ${text(item.semester)}`);const foot=el('footer');foot.append(el('span','',text(item.status,'approved')));const button=el('button','',item.deliveryType==='link'?'Open link':'Get download');button.addEventListener('click',async()=>{try{const {download}=await api.resources.download(item._id);window.open(download.url,'_blank','noopener')}catch(error){notice(error.message)}});foot.append(button);card.append(foot);return card},'No resources found');}
function renderEvents(){renderTiles('eventsGrid',state.events,(item)=>{const card=baseTile(text(item.type,'event'),item.title,text(item.description,'No description provided.'));const foot=el('footer');foot.append(el('span','',formatDate(item.eventDate)),el('span','',text(item.location,'Campus')));card.append(foot);return card},'No events scheduled');}
function renderReports(){renderTiles('lostFoundGrid',state.reports,(item)=>{const card=baseTile(`${item.type} · ${item.status}`,item.title,text(item.description));const foot=el('footer');foot.append(el('span','',text(item.category)),el('span','',text(item.location)));card.append(foot);return card},'No reports found');}
function renderProfile(){const panel=document.getElementById('profilePanel');clear(panel);const head=el('div','profile-head');head.append(el('div','profile-orb',initials(state.user.name)));const copy=el('div');copy.append(el('h2','',state.user.name),el('p','',state.user.email));head.append(copy);panel.append(head);const facts=el('div','profile-facts');[['Role',state.user.role],['Course',state.user.course],['Branch',state.user.branch],['Semester',state.user.currentSem],['Roll number',state.user.rollNumber],['Profile',state.user.profileCompleted?'Complete':'Incomplete']].forEach(([label,value])=>{const fact=el('div','fact');fact.append(el('span','',label),el('strong','',value));facts.append(fact)});panel.append(facts);}
async function renderAdmin(){const grid=document.getElementById('adminGrid');clear(grid);try{const [users,resources]=await Promise.all([api.admin.users({limit:100}),api.admin.resources({status:'pending',limit:100})]);[['Registered users',users.pagination?.total??users.items?.length??0],['Pending resources',resources.pagination?.total??resources.items?.length??0]].forEach(([label,value])=>{const card=el('div','window metric');card.append(el('span','',label),el('strong','',value));grid.append(card)})}catch(error){empty(grid,'Admin data unavailable',error.message)}}

async function loadResources(filters={}){const data=await api.resources.list({limit:50,...filters});state.resources=data.items||data.resources||[];renderResources();renderHome();}
async function bootstrap(){
  try{
    const me=await api.auth.me();state.user=me.user;document.getElementById('userName').textContent=state.user.name;document.getElementById('profileButton').textContent=initials(state.user.name);if(state.user.role==='admin')document.getElementById('adminNav').classList.remove('hidden');renderProfile();
    const results=await Promise.allSettled([api.courses.list({limit:100}),api.resources.list({limit:50}),api.events.list({upcoming:'true',limit:50}),api.lostFound.list({limit:50})]);
    const [courses,resources,events,reports]=results.map((result)=>result.status==='fulfilled'?result.value:null);state.courses=courses?.items||courses?.courses||[];state.resources=resources?.items||resources?.resources||[];state.events=events?.items||events?.events||[];state.reports=reports?.items||reports?.reports||[];
    renderHome();renderCourses();renderResources();renderEvents();renderReports();if(results.some((result)=>result.status==='rejected'))notice('Some campus services could not be loaded. You can still use the available sections.');
  }catch(error){if(error.status===401){window.location.href='login.html';return}notice(error.message);document.querySelectorAll('.skeleton').forEach((node)=>node.remove());}
}
function openView(name){document.querySelectorAll('.view').forEach((node)=>node.classList.toggle('active',node.id===`${name}View`));document.querySelectorAll('.nav-item').forEach((node)=>node.classList.toggle('active',node.dataset.view===name));document.getElementById('viewEyebrow').textContent=titles[name][0];document.getElementById('viewTitle').textContent=titles[name][1];if(name==='admin'&&state.user?.role==='admin')renderAdmin();history.replaceState(null,'',`#${name}`);document.querySelector('.sidebar').classList.remove('open');document.getElementById('mobileBackdrop').classList.add('hidden');}
document.getElementById('appNav').addEventListener('click',(event)=>{const button=event.target.closest('[data-view]');if(button)openView(button.dataset.view)});document.querySelectorAll('[data-open]').forEach((button)=>button.addEventListener('click',()=>openView(button.dataset.open)));document.getElementById('profileButton').addEventListener('click',()=>openView('profile'));document.getElementById('globalSearchButton').addEventListener('click',()=>{document.getElementById('resourceSearch').value=document.getElementById('globalSearch').value;openView('resources');loadResources({search:document.getElementById('globalSearch').value})});
let searchTimer;document.getElementById('resourceSearch').addEventListener('input',(event)=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadResources({search:event.target.value,resourceType:state.resourceType}),350)});document.getElementById('resourceFilters').addEventListener('click',(event)=>{const chip=event.target.closest('[data-type]');if(!chip)return;document.querySelectorAll('#resourceFilters .chip').forEach((node)=>node.classList.toggle('active',node===chip));state.resourceType=chip.dataset.type;loadResources({search:document.getElementById('resourceSearch').value,resourceType:state.resourceType})});document.getElementById('courseSearch').addEventListener('input',(event)=>{const value=event.target.value.toLowerCase();renderTiles('coursesGrid',state.courses.filter((item)=>`${item.code} ${item.name}`.toLowerCase().includes(value)),(item)=>baseTile(item.code,item.name,`${item.department} · Semester ${item.semester}`),'No courses found')});
document.getElementById('logoutBtn').addEventListener('click',async()=>{try{await api.auth.logout()}finally{window.location.href='login.html'}});document.getElementById('apiUrlSetting').value=localStorage.getItem('collegebuddy.apiBaseUrl')||'';document.getElementById('saveSettings').addEventListener('click',()=>{const value=document.getElementById('apiUrlSetting').value.trim().replace(/\/$/,'');if(value)localStorage.setItem('collegebuddy.apiBaseUrl',value);else localStorage.removeItem('collegebuddy.apiBaseUrl');notice('API setting saved. Reloading…');setTimeout(()=>location.reload(),500)});
const sidebar=document.querySelector('.sidebar'),backdrop=document.getElementById('mobileBackdrop');document.getElementById('menuButton').addEventListener('click',()=>{sidebar.classList.add('open');backdrop.classList.remove('hidden')});backdrop.addEventListener('click',()=>{sidebar.classList.remove('open');backdrop.classList.add('hidden')});setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),1000);openView(titles[location.hash.slice(1)]?location.hash.slice(1):'home');bootstrap();
